/**
 * Per-worktree Neon branch databases (issue #77).
 *
 * Every linked worktree shares one physical `.env.local` by symlink, so without this script
 * every worktree also shares one `DATABASE_URL`, and branches with different migration
 * lineages overwrite each other's schema.
 *
 * `setup` creates (or reuses) a Neon branch named after the current git branch, writes its
 * connection string to generated `.env.development.local` and `.env.production.local` files
 * in the worktree, and runs migrations against it. Both Next.js and Bun load those files
 * with higher precedence than `.env.local`, so the override applies to `next dev`,
 * `next build`/`next start`, and Bun scripts such as `db:migrate` without touching the
 * shared, read-only `.env.local`.
 *
 * `teardown` deletes that Neon branch and removes the generated files. Run it before
 * removing a worktree so Neon branches don't accumulate.
 *
 * Requires NEON_API_KEY and NEON_PROJECT_ID (see .env.example). When they are absent,
 * `setup` warns and leaves today's shared-database behaviour in place instead of failing.
 */

import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

const NEON_API_URL = "https://console.neon.tech/api/v2";

/** First line of every file this script generates; teardown only ever deletes files that
 * start with it, so a hand-written override is never destroyed. */
export const GENERATED_MARKER = "# Generated by scripts/worktree-db.ts. Do not edit by hand.";

/** Worktree-relative env files the override is written to. Next.js and Bun both load the
 * NODE_ENV-specific `.local` file above `.env.local`, which is what lets the override win. */
const OVERRIDE_FILES = [".env.development.local", ".env.production.local"];

/**
 * Minimal dotenv parser, used only to read DATABASE_URL out of the shared `.env.local`.
 * Multi-line quoted values (e.g. PICKUP_ADDRESS) are not reassembled; their continuation
 * lines parse as junk keys, which is fine because only DATABASE_URL is consumed.
 */
export function parseEnvFile(content: string): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();
    if (line === "" || line.startsWith("#")) {
      continue;
    }
    const separator = line.indexOf("=");
    if (separator <= 0) {
      continue;
    }
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    const quote = value[0];
    if ((quote === '"' || quote === "'") && value.length >= 2 && value.endsWith(quote)) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

/**
 * Endpoint host a connection string points at, with Neon's `-pooler` suffix stripped so it
 * matches the host reported by the endpoints API. Returns null when the URL is unparseable.
 */
export function endpointHostFromUrl(databaseUrl: string): string | null {
  let hostname: string;
  try {
    hostname = new URL(databaseUrl).hostname;
  } catch {
    return null;
  }
  if (hostname === "") {
    return null;
  }
  const [first, ...rest] = hostname.split(".");
  return [(first ?? "").replace(/-pooler$/, ""), ...rest].join(".");
}

/** Whether a connection string uses Neon's connection pooler. New overrides preserve this. */
export function isPooledUrl(databaseUrl: string): boolean {
  try {
    return new URL(databaseUrl).hostname.split(".")[0]?.endsWith("-pooler") ?? false;
  } catch {
    return false;
  }
}

export function renderOverrideEnv(input: {
  gitBranch: string;
  neonBranchId: string;
  databaseUrl: string;
}): string {
  return [
    GENERATED_MARKER,
    `# Neon branch database for git branch "${input.gitBranch}".`,
    "# Regenerate: bun run setup:worktree. Remove and delete the branch: bun run teardown:worktree.",
    `NEON_BRANCH_ID=${input.neonBranchId}`,
    `DATABASE_URL=${input.databaseUrl}`,
    "",
  ].join("\n");
}

/**
 * Neon branch id recorded in a generated override file, or null when the file was not
 * generated by this script. The id, not the branch name, is the durable link between a
 * worktree and its Neon branch: it survives git branch renames.
 */
export function generatedNeonBranchId(content: string): string | null {
  if (!content.startsWith(GENERATED_MARKER)) {
    return null;
  }
  return parseEnvFile(content).NEON_BRANCH_ID ?? null;
}

interface NeonBranch {
  id: string;
  name: string;
  default: boolean;
  protected: boolean;
}

interface NeonOperation {
  id: string;
  status: string;
}

/** Thin client over the Neon v2 REST API, scoped to one project. */
class NeonApi {
  constructor(
    private readonly apiKey: string,
    private readonly projectId: string,
  ) {}

  private async request<T>(
    pathname: string,
    init?: { method?: string; body?: unknown; allow404?: boolean },
  ): Promise<T | null> {
    const response = await fetch(`${NEON_API_URL}/projects/${this.projectId}${pathname}`, {
      method: init?.method ?? "GET",
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: init?.body === undefined ? undefined : JSON.stringify(init.body),
    });
    if (response.status === 404 && init?.allow404) {
      return null;
    }
    if (!response.ok) {
      // Neon error bodies carry codes and identifiers, never credentials, so they are safe
      // to surface in a terminal.
      const detail = await response.text();
      throw new Error(
        `Neon API ${init?.method ?? "GET"} ${pathname} failed (${response.status}): ${detail}`,
      );
    }
    return (await response.json()) as T;
  }

  async listBranches(): Promise<NeonBranch[]> {
    const data = await this.request<{ branches: NeonBranch[] }>("/branches");
    return data?.branches ?? [];
  }

  async getBranch(branchId: string): Promise<NeonBranch | null> {
    const data = await this.request<{ branch: NeonBranch }>(`/branches/${branchId}`, {
      allow404: true,
    });
    return data?.branch ?? null;
  }

  async createBranch(
    name: string,
    parentId: string,
  ): Promise<{ branch: NeonBranch; operations: NeonOperation[] }> {
    const data = await this.request<{ branch: NeonBranch; operations: NeonOperation[] }>(
      "/branches",
      {
        method: "POST",
        body: {
          branch: { name, parent_id: parentId },
          endpoints: [{ type: "read_write" }],
        },
      },
    );
    if (data === null) {
      throw new Error("Neon API returned no body for branch creation.");
    }
    return data;
  }

  async deleteBranch(branchId: string): Promise<void> {
    await this.request(`/branches/${branchId}`, { method: "DELETE", allow404: true });
  }

  async listEndpoints(): Promise<{ branch_id: string; host: string }[]> {
    const data = await this.request<{ endpoints: { branch_id: string; host: string }[] }>(
      "/endpoints",
    );
    return data?.endpoints ?? [];
  }

  async connectionUri(input: {
    branchId: string;
    database: string;
    role: string;
    pooled: boolean;
  }): Promise<string> {
    const query = new URLSearchParams({
      branch_id: input.branchId,
      database_name: input.database,
      role_name: input.role,
      pooled: String(input.pooled),
    });
    const data = await this.request<{ uri: string }>(`/connection_uri?${query}`);
    if (data === null) {
      throw new Error("Neon API returned no connection URI.");
    }
    return data.uri;
  }

  async getOperation(operationId: string): Promise<NeonOperation | null> {
    const data = await this.request<{ operation: NeonOperation }>(`/operations/${operationId}`, {
      allow404: true,
    });
    return data?.operation ?? null;
  }
}

/** Branch creation is async on Neon's side; wait so the first migration run doesn't race a
 * compute endpoint that is still provisioning. Exported for tests. */
export async function waitForOperations(
  api: Pick<NeonApi, "getOperation">,
  operations: NeonOperation[],
  pollIntervalMs = 2_000,
): Promise<void> {
  const deadline = Date.now() + 120_000;
  for (const started of operations) {
    let current: NeonOperation = started;
    while (current.status !== "finished") {
      if (
        current.status === "failed" ||
        current.status === "error" ||
        current.status === "cancelled"
      ) {
        throw new Error(`Neon operation ${current.id} ${current.status}.`);
      }
      if (Date.now() > deadline) {
        throw new Error("Timed out waiting for Neon branch operations to finish.");
      }
      await Bun.sleep(pollIntervalMs);
      const polled = await api.getOperation(started.id);
      if (polled === null) {
        // A 404 for an operation Neon just returned is a lookup failure, not completion.
        // Treating it as success would let migrations race a still-provisioning endpoint.
        throw new Error(`Neon operation ${started.id} disappeared before finishing.`);
      }
      current = polled;
    }
  }
}

function git(...args: string[]): string {
  const result = Bun.spawnSync(["git", ...args], { stdout: "pipe", stderr: "pipe" });
  if (result.exitCode !== 0) {
    throw new Error(`git ${args.join(" ")} failed: ${result.stderr.toString().trim()}`);
  }
  return result.stdout.toString().trim();
}

interface WorktreeContext {
  worktreeRoot: string;
  mainRoot: string;
  isLinkedWorktree: boolean;
}

function worktreeContext(): WorktreeContext {
  const worktreeRoot = git("rev-parse", "--show-toplevel");
  // The common dir is always inside the main checkout, even when run from a linked worktree.
  const mainRoot = path.dirname(git("rev-parse", "--path-format=absolute", "--git-common-dir"));
  return { worktreeRoot, mainRoot, isLinkedWorktree: worktreeRoot !== mainRoot };
}

/** Existing override files, split by whether this script generated them. Manual files are
 * deliberate developer overrides and are never rewritten or deleted. */
function readOverrideFiles(worktreeRoot: string): {
  generated: { filePath: string; neonBranchId: string | null }[];
  manual: string[];
} {
  const generated: { filePath: string; neonBranchId: string | null }[] = [];
  const manual: string[] = [];
  for (const name of OVERRIDE_FILES) {
    const filePath = path.join(worktreeRoot, name);
    if (!existsSync(filePath)) {
      continue;
    }
    const content = readFileSync(filePath, "utf8");
    if (content.startsWith(GENERATED_MARKER)) {
      generated.push({ filePath, neonBranchId: generatedNeonBranchId(content) });
    } else {
      manual.push(filePath);
    }
  }
  return { generated, manual };
}

async function setup(): Promise<void> {
  const { worktreeRoot, mainRoot, isLinkedWorktree } = worktreeContext();
  if (!isLinkedWorktree) {
    console.log("Main checkout keeps the shared database; skipping Neon branch setup.");
    return;
  }

  const apiKey = process.env.NEON_API_KEY;
  const projectId = process.env.NEON_PROJECT_ID;
  if (!apiKey || !projectId) {
    console.warn(
      "NEON_API_KEY and NEON_PROJECT_ID are not both set, so this worktree keeps the shared " +
        "DATABASE_URL and shares migration state with every other worktree (issue #77). Add " +
        "both to the main checkout's .env.local, then re-run `bun run setup:worktree` to give " +
        "this worktree its own Neon branch database.",
    );
    return;
  }

  const gitBranch = git("rev-parse", "--abbrev-ref", "HEAD");
  if (gitBranch === "HEAD") {
    console.warn("Detached HEAD; skipping Neon branch setup until a branch is checked out.");
    return;
  }

  const sharedEnvPath = path.join(mainRoot, ".env.local");
  if (!existsSync(sharedEnvPath)) {
    console.warn(`No ${sharedEnvPath}; skipping Neon branch setup.`);
    return;
  }
  // Read the shared file directly instead of process.env: a previously generated override
  // would already have replaced DATABASE_URL in this process's environment.
  const sharedUrl = parseEnvFile(readFileSync(sharedEnvPath, "utf8")).DATABASE_URL;
  if (!sharedUrl) {
    console.warn("Shared .env.local has no DATABASE_URL to branch from; skipping.");
    return;
  }
  let parsedShared: URL;
  try {
    parsedShared = new URL(sharedUrl);
  } catch {
    // Deliberately does not echo the URL: it carries the database password.
    throw new Error("The shared DATABASE_URL is not a parseable connection string.");
  }
  const role = decodeURIComponent(parsedShared.username);
  const database = decodeURIComponent(parsedShared.pathname.slice(1));
  if (!role || !database) {
    throw new Error("Could not read role and database name from the shared DATABASE_URL.");
  }

  const { generated, manual } = readOverrideFiles(worktreeRoot);
  if (manual.length > 0) {
    throw new Error(
      `Refusing to overwrite manual env override(s): ${manual.join(", ")}. Remove them or ` +
        "keep managing DATABASE_URL yourself.",
    );
  }

  const api = new NeonApi(apiKey, projectId);

  // A branch id recorded by a previous run wins over a name lookup: it survives git branch
  // renames and prevents orphaned Neon branches.
  const recordedId = generated.find((file) => file.neonBranchId !== null)?.neonBranchId ?? null;
  let branch = recordedId ? await api.getBranch(recordedId) : null;
  if (branch === null) {
    branch = (await api.listBranches()).find((candidate) => candidate.name === gitBranch) ?? null;
  }

  if (branch === null) {
    // Fork from the branch the shared DATABASE_URL points at (the dev branch), never
    // implicitly from the project's default branch, which may hold production data.
    // `||` because an unfilled `NEON_PARENT_BRANCH_ID=` line yields an empty string.
    let parentId = process.env.NEON_PARENT_BRANCH_ID || null;
    if (parentId === null) {
      const sharedHost = endpointHostFromUrl(sharedUrl);
      parentId =
        (await api.listEndpoints()).find((endpoint) => endpoint.host === sharedHost)?.branch_id ??
        null;
    }
    if (parentId === null) {
      throw new Error(
        "Could not resolve which Neon branch the shared DATABASE_URL points at. Set " +
          "NEON_PARENT_BRANCH_ID in the main checkout's .env.local to choose the parent branch.",
      );
    }
    console.log(`Creating Neon branch "${gitBranch}" from parent ${parentId}...`);
    const created = await api.createBranch(gitBranch, parentId);
    await waitForOperations(api, created.operations);
    branch = created.branch;
  } else {
    console.log(`Reusing existing Neon branch "${branch.name}" (${branch.id}).`);
  }

  const databaseUrl = await api.connectionUri({
    branchId: branch.id,
    database,
    role,
    pooled: isPooledUrl(sharedUrl),
  });

  const content = renderOverrideEnv({ gitBranch, neonBranchId: branch.id, databaseUrl });
  for (const name of OVERRIDE_FILES) {
    writeFileSync(path.join(worktreeRoot, name), content);
  }
  console.log(`Wrote ${OVERRIDE_FILES.join(" and ")} pointing at Neon branch ${branch.id}.`);

  console.log("Running migrations against the worktree's Neon branch...");
  const migrate = Bun.spawnSync(["bun", "run", "db:migrate"], {
    cwd: worktreeRoot,
    env: { ...process.env, DATABASE_URL: databaseUrl },
    stdout: "inherit",
    stderr: "inherit",
  });
  if (migrate.exitCode !== 0) {
    throw new Error(
      "Migrations failed against the new Neon branch. Fix the failure and re-run " +
        "`bun run setup:worktree`; the override files above are already in place.",
    );
  }
  console.log(`Worktree database ready (Neon branch "${branch.name}").`);
}

async function teardown(): Promise<void> {
  const { worktreeRoot, isLinkedWorktree } = worktreeContext();
  if (!isLinkedWorktree) {
    throw new Error("Refusing to run teardown in the main checkout.");
  }

  const { generated, manual } = readOverrideFiles(worktreeRoot);
  for (const filePath of manual) {
    console.warn(`Leaving ${filePath} alone; it was not generated by this script.`);
  }
  if (generated.length === 0) {
    console.log("No generated database override found; nothing to tear down.");
    return;
  }

  const neonBranchId = generated.find((file) => file.neonBranchId !== null)?.neonBranchId ?? null;
  if (neonBranchId !== null) {
    const apiKey = process.env.NEON_API_KEY;
    const projectId = process.env.NEON_PROJECT_ID;
    if (!apiKey || !projectId) {
      throw new Error(
        `Cannot delete Neon branch ${neonBranchId} without NEON_API_KEY and NEON_PROJECT_ID. ` +
          "Set them in the main checkout's .env.local and re-run `bun run teardown:worktree`.",
      );
    }
    const api = new NeonApi(apiKey, projectId);
    const branch = await api.getBranch(neonBranchId);
    if (branch === null) {
      console.log(`Neon branch ${neonBranchId} is already gone.`);
    } else if (branch.default || branch.protected) {
      throw new Error(
        `Refusing to delete Neon branch "${branch.name}" (${branch.id}): it is ` +
          `${branch.default ? "the default" : "a protected"} branch.`,
      );
    } else {
      await api.deleteBranch(branch.id);
      console.log(`Deleted Neon branch "${branch.name}" (${branch.id}).`);
    }
  }

  for (const file of generated) {
    rmSync(file.filePath);
    console.log(`Removed ${file.filePath}.`);
  }
}

if (import.meta.main) {
  const command = process.argv[2];
  try {
    if (command === "setup") {
      await setup();
    } else if (command === "teardown") {
      await teardown();
    } else {
      console.error("Usage: bun scripts/worktree-db.ts <setup|teardown>");
      process.exit(1);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
