/**
 * Per-worktree Neon branch databases (issue #77).
 *
 * Every linked worktree shares one physical `.env.local` by symlink, so without this script
 * every worktree also shares one `DATABASE_URL`, and branches with different migration
 * lineages overwrite each other's schema.
 *
 * `setup` creates (or reuses) a Neon branch named after the current git branch, writes its
 * connection string to generated `.env.development.local` and `.env.production.local` files
 * in the worktree, and runs migrations against it. Both Next.js and Bun load those files
 * with higher precedence than `.env.local`, so the override applies to `next dev`,
 * `next build`/`next start`, and Bun scripts such as `db:migrate` without touching the
 * shared, read-only `.env.local`.
 *
 * `teardown` deletes that Neon branch and removes the generated files. Run it before
 * removing a worktree so Neon branches don't accumulate. With `--if-merged` (issue #121) it
 * becomes safe to run unconditionally from inside the worktree: it fetches origin/main and
 * no-ops unless the checked-out branch is merged and the worktree is settled (no uncommitted
 * changes, no commits origin/main lacks).
 *
 * `prune` (issue #105) runs from the main checkout and cleans up what manual teardown
 * misses: it lists worktrees whose git branch is merged into origin/main plus Neon branches
 * no worktree references at all, and deletes both kinds when re-run with `--yes`. Merged
 * worktrees that are not settled are skipped with the reason printed — a merged branch a
 * developer is still working in must keep its database (issue #121). Prune only removes the
 * Neon branch and generated env files — the worktree and git branch stay, so a settled
 * T3 Code thread keeps working and `setup` can recreate the database later.
 *
 * Requires NEON_API_KEY and NEON_PROJECT_ID (see .env.example). When they are absent,
 * `setup` warns and leaves today's shared-database behaviour in place instead of failing.
 */

import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

const NEON_API_URL = "https://console.neon.tech/api/v2";

/** First line of every file this script generates; teardown only ever deletes files that
 * start with it, so a hand-written override is never destroyed. */
export const GENERATED_MARKER = "# Generated by scripts/worktree-db.ts. Do not edit by hand.";

/** Worktree-relative env files the override is written to. Next.js and Bun both load the
 * NODE_ENV-specific `.local` file above `.env.local`, which is what lets the override win. */
const OVERRIDE_FILES = [".env.development.local", ".env.production.local"];

/**
 * Minimal dotenv parser, used only to read DATABASE_URL out of the shared `.env.local`.
 * Multi-line quoted values are not reassembled; their continuation
 * lines parse as junk keys, which is fine because only DATABASE_URL is consumed.
 */
export function parseEnvFile(content: string): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();
    if (line === "" || line.startsWith("#")) {
      continue;
    }
    const separator = line.indexOf("=");
    if (separator <= 0) {
      continue;
    }
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    const quote = value[0];
    if ((quote === '"' || quote === "'") && value.length >= 2 && value.endsWith(quote)) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
  return vars;
}

/**
 * Endpoint host a connection string points at, with Neon's `-pooler` suffix stripped so it
 * matches the host reported by the endpoints API. Returns null when the URL is unparseable.
 */
export function endpointHostFromUrl(databaseUrl: string): string | null {
  let hostname: string;
  try {
    hostname = new URL(databaseUrl).hostname;
  } catch {
    return null;
  }
  if (hostname === "") {
    return null;
  }
  const [first, ...rest] = hostname.split(".");
  return [(first ?? "").replace(/-pooler$/, ""), ...rest].join(".");
}

/** Whether a connection string uses Neon's connection pooler. New overrides preserve this. */
export function isPooledUrl(databaseUrl: string): boolean {
  try {
    return new URL(databaseUrl).hostname.split(".")[0]?.endsWith("-pooler") ?? false;
  } catch {
    return false;
  }
}

export function renderOverrideEnv(input: {
  gitBranch: string;
  neonBranchId: string;
  databaseUrl: string;
}): string {
  return [
    GENERATED_MARKER,
    `# Neon branch database for git branch "${input.gitBranch}".`,
    "# Regenerate: bun run setup:worktree. Remove and delete the branch: bun run teardown:worktree.",
    `NEON_BRANCH_ID=${input.neonBranchId}`,
    `DATABASE_URL=${input.databaseUrl}`,
    "",
  ].join("\n");
}

/**
 * Neon branch id recorded in a generated override file, or null when the file was not
 * generated by this script. The id, not the branch name, is the durable link between a
 * worktree and its Neon branch: it survives git branch renames.
 */
export function generatedNeonBranchId(content: string): string | null {
  if (!content.startsWith(GENERATED_MARKER)) {
    return null;
  }
  return parseEnvFile(content).NEON_BRANCH_ID ?? null;
}

export interface NeonBranch {
  id: string;
  name: string;
  default: boolean;
  protected: boolean;
}

interface NeonOperation {
  id: string;
  status: string;
}

/** Thin client over the Neon v2 REST API, scoped to one project. */
class NeonApi {
  constructor(
    private readonly apiKey: string,
    private readonly projectId: string,
  ) {}

  private async request<T>(
    pathname: string,
    init?: { method?: string; body?: unknown; allow404?: boolean },
  ): Promise<T | null> {
    const response = await fetch(`${NEON_API_URL}/projects/${this.projectId}${pathname}`, {
      method: init?.method ?? "GET",
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: init?.body === undefined ? undefined : JSON.stringify(init.body),
    });
    if (response.status === 404 && init?.allow404) {
      return null;
    }
    if (!response.ok) {
      // Neon error bodies carry codes and identifiers, never credentials, so they are safe
      // to surface in a terminal.
      const detail = await response.text();
      throw new Error(
        `Neon API ${init?.method ?? "GET"} ${pathname} failed (${response.status}): ${detail}`,
      );
    }
    return (await response.json()) as T;
  }

  async listBranches(): Promise<NeonBranch[]> {
    const data = await this.request<{ branches: NeonBranch[] }>("/branches");
    return data?.branches ?? [];
  }

  async getBranch(branchId: string): Promise<NeonBranch | null> {
    const data = await this.request<{ branch: NeonBranch }>(`/branches/${branchId}`, {
      allow404: true,
    });
    return data?.branch ?? null;
  }

  async createBranch(
    name: string,
    parentId: string,
  ): Promise<{ branch: NeonBranch; operations: NeonOperation[] }> {
    const data = await this.request<{ branch: NeonBranch; operations: NeonOperation[] }>(
      "/branches",
      {
        method: "POST",
        body: {
          branch: { name, parent_id: parentId },
          endpoints: [{ type: "read_write" }],
        },
      },
    );
    if (data === null) {
      throw new Error("Neon API returned no body for branch creation.");
    }
    return data;
  }

  async deleteBranch(branchId: string): Promise<void> {
    await this.request(`/branches/${branchId}`, { method: "DELETE", allow404: true });
  }

  async listEndpoints(): Promise<{ branch_id: string; host: string }[]> {
    const data = await this.request<{ endpoints: { branch_id: string; host: string }[] }>(
      "/endpoints",
    );
    return data?.endpoints ?? [];
  }

  async connectionUri(input: {
    branchId: string;
    database: string;
    role: string;
    pooled: boolean;
  }): Promise<string> {
    const query = new URLSearchParams({
      branch_id: input.branchId,
      database_name: input.database,
      role_name: input.role,
      pooled: String(input.pooled),
    });
    const data = await this.request<{ uri: string }>(`/connection_uri?${query}`);
    if (data === null) {
      throw new Error("Neon API returned no connection URI.");
    }
    return data.uri;
  }

  async getOperation(operationId: string): Promise<NeonOperation | null> {
    const data = await this.request<{ operation: NeonOperation }>(`/operations/${operationId}`, {
      allow404: true,
    });
    return data?.operation ?? null;
  }
}

/** Branch creation is async on Neon's side; wait so the first migration run doesn't race a
 * compute endpoint that is still provisioning. Exported for tests. */
export async function waitForOperations(
  api: Pick<NeonApi, "getOperation">,
  operations: NeonOperation[],
  pollIntervalMs = 2_000,
): Promise<void> {
  const deadline = Date.now() + 120_000;
  for (const started of operations) {
    let current: NeonOperation = started;
    while (current.status !== "finished") {
      if (
        current.status === "failed" ||
        current.status === "error" ||
        current.status === "cancelled"
      ) {
        throw new Error(`Neon operation ${current.id} ${current.status}.`);
      }
      if (Date.now() > deadline) {
        throw new Error("Timed out waiting for Neon branch operations to finish.");
      }
      await Bun.sleep(pollIntervalMs);
      const polled = await api.getOperation(started.id);
      if (polled === null) {
        // A 404 for an operation Neon just returned is a lookup failure, not completion.
        // Treating it as success would let migrations race a still-provisioning endpoint.
        throw new Error(`Neon operation ${started.id} disappeared before finishing.`);
      }
      current = polled;
    }
  }
}

/** Neon API client from NEON_API_KEY/NEON_PROJECT_ID, or an actionable error telling the
 * developer where to set them and which command to re-run. */
function requireApi(rerunCommand: string): NeonApi {
  const apiKey = process.env.NEON_API_KEY;
  const projectId = process.env.NEON_PROJECT_ID;
  if (!apiKey || !projectId) {
    throw new Error(
      "NEON_API_KEY and NEON_PROJECT_ID are required. Set them in the main checkout's " +
        `.env.local and re-run \`${rerunCommand}\`.`,
    );
  }
  return new NeonApi(apiKey, projectId);
}

/**
 * Neon branch id the shared DATABASE_URL points at — the dev branch worktree databases fork
 * from. Prefers an explicit NEON_PARENT_BRANCH_ID; otherwise matches the URL's endpoint host
 * against the project's endpoints. Null when neither resolves.
 */
async function resolveParentBranchId(api: NeonApi, sharedUrl: string): Promise<string | null> {
  // `||` because an unfilled `NEON_PARENT_BRANCH_ID=` line yields an empty string.
  const fromEnv = process.env.NEON_PARENT_BRANCH_ID || null;
  if (fromEnv !== null) {
    return fromEnv;
  }
  const sharedHost = endpointHostFromUrl(sharedUrl);
  return (
    (await api.listEndpoints()).find((endpoint) => endpoint.host === sharedHost)?.branch_id ?? null
  );
}

function git(...args: string[]): string {
  const result = Bun.spawnSync(["git", ...args], { stdout: "pipe", stderr: "pipe" });
  if (result.exitCode !== 0) {
    throw new Error(`git ${args.join(" ")} failed: ${result.stderr.toString().trim()}`);
  }
  return result.stdout.toString().trim();
}

interface WorktreeContext {
  worktreeRoot: string;
  mainRoot: string;
  isLinkedWorktree: boolean;
}

function worktreeContext(): WorktreeContext {
  const worktreeRoot = git("rev-parse", "--show-toplevel");
  // The common dir is always inside the main checkout, even when run from a linked worktree.
  const mainRoot = path.dirname(git("rev-parse", "--path-format=absolute", "--git-common-dir"));
  return { worktreeRoot, mainRoot, isLinkedWorktree: worktreeRoot !== mainRoot };
}

/** Existing override files, split by whether this script generated them. Manual files are
 * deliberate developer overrides and are never rewritten or deleted. */
function readOverrideFiles(worktreeRoot: string): {
  generated: { filePath: string; neonBranchId: string | null }[];
  manual: string[];
} {
  const generated: { filePath: string; neonBranchId: string | null }[] = [];
  const manual: string[] = [];
  for (const name of OVERRIDE_FILES) {
    const filePath = path.join(worktreeRoot, name);
    if (!existsSync(filePath)) {
      continue;
    }
    const content = readFileSync(filePath, "utf8");
    if (content.startsWith(GENERATED_MARKER)) {
      generated.push({ filePath, neonBranchId: generatedNeonBranchId(content) });
    } else {
      manual.push(filePath);
    }
  }
  return { generated, manual };
}

async function setup(): Promise<void> {
  const { worktreeRoot, mainRoot, isLinkedWorktree } = worktreeContext();
  if (!isLinkedWorktree) {
    console.log("Main checkout keeps the shared database; skipping Neon branch setup.");
    return;
  }

  const apiKey = process.env.NEON_API_KEY;
  const projectId = process.env.NEON_PROJECT_ID;
  if (!apiKey || !projectId) {
    console.warn(
      "NEON_API_KEY and NEON_PROJECT_ID are not both set, so this worktree keeps the shared " +
        "DATABASE_URL and shares migration state with every other worktree (issue #77). Add " +
        "both to the main checkout's .env.local, then re-run `bun run setup:worktree` to give " +
        "this worktree its own Neon branch database.",
    );
    return;
  }

  const gitBranch = git("rev-parse", "--abbrev-ref", "HEAD");
  if (gitBranch === "HEAD") {
    console.warn("Detached HEAD; skipping Neon branch setup until a branch is checked out.");
    return;
  }

  const sharedEnvPath = path.join(mainRoot, ".env.local");
  if (!existsSync(sharedEnvPath)) {
    console.warn(`No ${sharedEnvPath}; skipping Neon branch setup.`);
    return;
  }
  // Read the shared file directly instead of process.env: a previously generated override
  // would already have replaced DATABASE_URL in this process's environment.
  const sharedUrl = parseEnvFile(readFileSync(sharedEnvPath, "utf8")).DATABASE_URL;
  if (!sharedUrl) {
    console.warn("Shared .env.local has no DATABASE_URL to branch from; skipping.");
    return;
  }
  let parsedShared: URL;
  try {
    parsedShared = new URL(sharedUrl);
  } catch {
    // Deliberately does not echo the URL: it carries the database password.
    throw new Error("The shared DATABASE_URL is not a parseable connection string.");
  }
  const role = decodeURIComponent(parsedShared.username);
  const database = decodeURIComponent(parsedShared.pathname.slice(1));
  if (!role || !database) {
    throw new Error("Could not read role and database name from the shared DATABASE_URL.");
  }

  const { generated, manual } = readOverrideFiles(worktreeRoot);
  if (manual.length > 0) {
    throw new Error(
      `Refusing to overwrite manual env override(s): ${manual.join(", ")}. Remove them or ` +
        "keep managing DATABASE_URL yourself.",
    );
  }

  const api = new NeonApi(apiKey, projectId);

  // A branch id recorded by a previous run wins over a name lookup: it survives git branch
  // renames and prevents orphaned Neon branches.
  const recordedId = generated.find((file) => file.neonBranchId !== null)?.neonBranchId ?? null;
  let branch = recordedId ? await api.getBranch(recordedId) : null;
  if (branch === null) {
    branch = (await api.listBranches()).find((candidate) => candidate.name === gitBranch) ?? null;
  }

  if (branch === null) {
    // Fork from the branch the shared DATABASE_URL points at (the dev branch), never
    // implicitly from the project's default branch, which may hold production data.
    const parentId = await resolveParentBranchId(api, sharedUrl);
    if (parentId === null) {
      throw new Error(
        "Could not resolve which Neon branch the shared DATABASE_URL points at. Set " +
          "NEON_PARENT_BRANCH_ID in the main checkout's .env.local to choose the parent branch.",
      );
    }
    console.log(`Creating Neon branch "${gitBranch}" from parent ${parentId}...`);
    const created = await api.createBranch(gitBranch, parentId);
    await waitForOperations(api, created.operations);
    branch = created.branch;
  } else {
    console.log(`Reusing existing Neon branch "${branch.name}" (${branch.id}).`);
  }

  const databaseUrl = await api.connectionUri({
    branchId: branch.id,
    database,
    role,
    pooled: isPooledUrl(sharedUrl),
  });

  const content = renderOverrideEnv({ gitBranch, neonBranchId: branch.id, databaseUrl });
  for (const name of OVERRIDE_FILES) {
    writeFileSync(path.join(worktreeRoot, name), content);
  }
  console.log(`Wrote ${OVERRIDE_FILES.join(" and ")} pointing at Neon branch ${branch.id}.`);

  console.log("Running migrations against the worktree's Neon branch...");
  const migrate = Bun.spawnSync(["bun", "run", "db:migrate"], {
    cwd: worktreeRoot,
    env: { ...process.env, DATABASE_URL: databaseUrl },
    stdout: "inherit",
    stderr: "inherit",
  });
  if (migrate.exitCode !== 0) {
    throw new Error(
      "Migrations failed against the new Neon branch. Fix the failure and re-run " +
        "`bun run setup:worktree`; the override files above are already in place.",
    );
  }
  console.log(`Worktree database ready (Neon branch "${branch.name}").`);
}

/**
 * Deletes the Neon branch recorded in a worktree's generated override files and removes those
 * files. `getApi` is called only when a branch id was actually recorded, so file-only cleanup
 * still works without credentials. Shared by `teardown` (the current worktree) and `prune`
 * (each merged worktree). Default and protected Neon branches are never deleted.
 */
async function removeWorktreeDatabase(worktreeRoot: string, getApi: () => NeonApi): Promise<void> {
  const { generated, manual } = readOverrideFiles(worktreeRoot);
  for (const filePath of manual) {
    console.warn(`Leaving ${filePath} alone; it was not generated by this script.`);
  }
  if (generated.length === 0) {
    console.log(`No generated database override in ${worktreeRoot}; nothing to remove.`);
    return;
  }

  const neonBranchId = generated.find((file) => file.neonBranchId !== null)?.neonBranchId ?? null;
  if (neonBranchId !== null) {
    const api = getApi();
    const branch = await api.getBranch(neonBranchId);
    if (branch === null) {
      console.log(`Neon branch ${neonBranchId} is already gone.`);
    } else if (branch.default || branch.protected) {
      throw new Error(
        `Refusing to delete Neon branch "${branch.name}" (${branch.id}): it is ` +
          `${branch.default ? "the default" : "a protected"} branch.`,
      );
    } else {
      await api.deleteBranch(branch.id);
      console.log(`Deleted Neon branch "${branch.name}" (${branch.id}).`);
    }
  }

  for (const file of generated) {
    rmSync(file.filePath);
    console.log(`Removed ${file.filePath}.`);
  }
}

/**
 * Why a worktree is still in use and must keep its database, or null when it is settled.
 * Uncommitted changes or commits origin/main does not contain mean follow-up work is
 * happening in place even though the branch is merged, so teardown and prune both skip it.
 */
function worktreeUnsettledReason(worktreeRoot: string): string | null {
  if (git("-C", worktreeRoot, "status", "--porcelain") !== "") {
    return "uncommitted changes";
  }
  if (git("-C", worktreeRoot, "rev-list", "--count", "HEAD", "--not", "origin/main") !== "0") {
    return "commits not in origin/main";
  }
  return null;
}

/**
 * With `ifMerged`, the guards make this safe to run unconditionally after a PR merges: a
 * guard that fails is a no-op exit 0, not an error, so agent workflows can always call it.
 */
async function teardown(ifMerged: boolean): Promise<void> {
  const { worktreeRoot, isLinkedWorktree } = worktreeContext();
  if (!isLinkedWorktree) {
    throw new Error("Refusing to run teardown in the main checkout.");
  }
  if (ifMerged) {
    // Judge merged-ness against the real remote, never stale local refs. The explicit forced
    // refspec updates refs/remotes/origin/main even under a restrictive fetch refmap (e.g. a
    // single-branch clone) or a rewritten remote history, where a plain `fetch origin main`
    // would only touch FETCH_HEAD and leave the guards reading a stale ref.
    git("fetch", "origin", "+main:refs/remotes/origin/main");
    const branch = git("rev-parse", "--abbrev-ref", "HEAD");
    if (branch === "HEAD") {
      console.log("Detached HEAD; not tearing down.");
      return;
    }
    if (!isMergedIntoMain(branch)) {
      console.log(`Branch "${branch}" is not merged into origin/main; nothing done.`);
      return;
    }
    const reason = worktreeUnsettledReason(worktreeRoot);
    if (reason !== null) {
      console.log(`Worktree still in use (${reason}); nothing done.`);
      return;
    }
  }
  await removeWorktreeDatabase(worktreeRoot, () => requireApi("bun run teardown:worktree"));
}

/** One linked worktree as seen by `prune`, with everything classification needs. */
export interface PruneWorktree {
  path: string;
  /** Checked-out branch name, or null when the worktree is detached. */
  branch: string | null;
  /** Neon branch id recorded in the worktree's generated override files, if any. */
  neonBranchId: string | null;
  hasGeneratedOverrides: boolean;
  /** Whether the checked-out branch is already contained in origin/main. */
  merged: boolean;
  /** Why the worktree is still in use (see worktreeUnsettledReason), or null when settled. */
  unsettledReason: string | null;
}

/** Worktree paths and checked-out branch names from `git worktree list --porcelain`.
 * `branch` is null for detached or bare entries. */
export function parseWorktreeList(porcelain: string): { path: string; branch: string | null }[] {
  const entries: { path: string; branch: string | null }[] = [];
  for (const block of porcelain.split("\n\n")) {
    const lines = block.split("\n");
    const pathLine = lines.find((line) => line.startsWith("worktree "));
    if (pathLine === undefined) {
      continue;
    }
    const branchLine = lines.find((line) => line.startsWith("branch refs/heads/"));
    entries.push({
      path: pathLine.slice("worktree ".length),
      branch: branchLine?.slice("branch refs/heads/".length) ?? null,
    });
  }
  return entries;
}

/**
 * Splits cleanup work into the two kinds `prune` handles: worktrees whose branch is merged
 * (their database and override files can go) and Neon branches nothing references (a worktree
 * was deleted without teardown). Merged worktrees that are unsettled (issue #121) come back
 * as `skippedWorktrees` for reporting instead — still in use, never deleted. A branch
 * referenced by any worktree — merged or not — is never an orphan, and default, protected,
 * and explicitly excluded branches (the shared dev branch) are never candidates — a merged
 * worktree whose override somehow records an excluded id is skipped rather than torn down,
 * so the dev branch cannot be deleted through either path.
 */
export function classifyPrune(input: {
  neonBranches: NeonBranch[];
  worktrees: PruneWorktree[];
  excludedBranchIds: Set<string>;
}): {
  mergedWorktrees: PruneWorktree[];
  skippedWorktrees: PruneWorktree[];
  orphanBranches: NeonBranch[];
} {
  const referenced = new Set(
    input.worktrees.map((worktree) => worktree.neonBranchId).filter((id) => id !== null),
  );
  const candidates = input.worktrees.filter(
    (worktree) =>
      worktree.merged &&
      worktree.hasGeneratedOverrides &&
      (worktree.neonBranchId === null || !input.excludedBranchIds.has(worktree.neonBranchId)),
  );
  return {
    mergedWorktrees: candidates.filter((worktree) => worktree.unsettledReason === null),
    skippedWorktrees: candidates.filter((worktree) => worktree.unsettledReason !== null),
    orphanBranches: input.neonBranches.filter(
      (branch) =>
        !branch.default &&
        !branch.protected &&
        !input.excludedBranchIds.has(branch.id) &&
        !referenced.has(branch.id),
    ),
  };
}

/** True when `branch` is already contained in origin/main. Any non-zero exit (including an
 * unknown ref) counts as not merged, which errs toward keeping databases alive. */
function isMergedIntoMain(branch: string): boolean {
  const result = Bun.spawnSync(
    ["git", "merge-base", "--is-ancestor", `refs/heads/${branch}`, "origin/main"],
    { stdout: "pipe", stderr: "pipe" },
  );
  return result.exitCode === 0;
}

async function prune(confirmed: boolean): Promise<void> {
  const { mainRoot, isLinkedWorktree } = worktreeContext();
  if (isLinkedWorktree) {
    throw new Error("Run prune from the main checkout; it sweeps every linked worktree.");
  }
  const api = requireApi("bun run worktree:prune");

  const sharedEnvPath = path.join(mainRoot, ".env.local");
  const sharedUrl = existsSync(sharedEnvPath)
    ? parseEnvFile(readFileSync(sharedEnvPath, "utf8")).DATABASE_URL
    : undefined;
  // The shared dev branch is excluded from orphan candidates by id, never by name pattern.
  // Refuse to classify anything when it cannot be identified.
  const parentId = sharedUrl === undefined ? null : await resolveParentBranchId(api, sharedUrl);
  if (parentId === null) {
    throw new Error(
      "Could not identify the shared dev branch to exclude from pruning. Set " +
        "NEON_PARENT_BRANCH_ID in the main checkout's .env.local and re-run.",
    );
  }

  // Merged-ness is judged against the remote main so stale local state cannot cause a delete.
  // Forced refspec for the same reason as in teardown: refresh refs/remotes/origin/main itself.
  git("fetch", "origin", "+main:refs/remotes/origin/main");

  const worktrees = parseWorktreeList(git("worktree", "list", "--porcelain"))
    .filter((entry) => entry.path !== mainRoot)
    .map((entry) => {
      const { generated } = readOverrideFiles(entry.path);
      const merged = entry.branch !== null && isMergedIntoMain(entry.branch);
      return {
        path: entry.path,
        branch: entry.branch,
        neonBranchId: generated.find((file) => file.neonBranchId !== null)?.neonBranchId ?? null,
        hasGeneratedOverrides: generated.length > 0,
        merged,
        // Only merged worktrees can become teardown candidates, so only they need the check.
        unsettledReason: merged ? worktreeUnsettledReason(entry.path) : null,
      };
    });

  const { mergedWorktrees, skippedWorktrees, orphanBranches } = classifyPrune({
    neonBranches: await api.listBranches(),
    worktrees,
    excludedBranchIds: new Set([parentId]),
  });

  for (const worktree of skippedWorktrees) {
    console.log(
      `Still in use (${worktree.unsettledReason}): ${worktree.path} ("${worktree.branch}") — ` +
        "keeping its database.",
    );
  }
  if (mergedWorktrees.length === 0 && orphanBranches.length === 0) {
    console.log("Nothing to prune: no merged worktree databases and no orphaned Neon branches.");
    return;
  }
  for (const worktree of mergedWorktrees) {
    console.log(
      `Merged into main: ${worktree.path} ("${worktree.branch}") — ` +
        `Neon branch ${worktree.neonBranchId ?? "none recorded, override files only"}.`,
    );
  }
  for (const branch of orphanBranches) {
    console.log(`Orphaned Neon branch: "${branch.name}" (${branch.id}) — no worktree uses it.`);
  }
  if (!confirmed) {
    console.log("Dry run; nothing deleted. Re-run with --yes to delete the above.");
    return;
  }

  for (const worktree of mergedWorktrees) {
    await removeWorktreeDatabase(worktree.path, () => api);
  }
  for (const branch of orphanBranches) {
    await api.deleteBranch(branch.id);
    console.log(`Deleted orphaned Neon branch "${branch.name}" (${branch.id}).`);
  }
}

if (import.meta.main) {
  const command = process.argv[2];
  try {
    if (command === "setup") {
      await setup();
    } else if (command === "teardown") {
      await teardown(process.argv.includes("--if-merged"));
    } else if (command === "prune") {
      await prune(process.argv.includes("--yes"));
    } else {
      console.error(
        "Usage: bun scripts/worktree-db.ts <setup|teardown [--if-merged]|prune [--yes]>",
      );
      process.exit(1);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
